// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetAccessor(ctx context.Context, username string) (Accessor, error)
	InsertAccessor(ctx context.Context, arg InsertAccessorParams) (sql.Result, error)
	UpdateAccessor(ctx context.Context, arg UpdateAccessorParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
