// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const getAccessor = `-- name: GetAccessor :one
SELECT username, hashed_password FROM accessors WHERE username = ?
`

func (q *Queries) GetAccessor(ctx context.Context, username string) (Accessor, error) {
	row := q.db.QueryRowContext(ctx, getAccessor, username)
	var i Accessor
	err := row.Scan(&i.Username, &i.HashedPassword)
	return i, err
}

const insertAccessor = `-- name: InsertAccessor :execresult
INSERT INTO accessors (username, hashed_password) VALUES (?, ?)
`

type InsertAccessorParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) InsertAccessor(ctx context.Context, arg InsertAccessorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAccessor, arg.Username, arg.HashedPassword)
}

const updateAccessor = `-- name: UpdateAccessor :execresult
UPDATE accessors SET username = ?, hashed_password = ? WHERE username = ?
`

type UpdateAccessorParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	Username_2     string `json:"username_2"`
}

func (q *Queries) UpdateAccessor(ctx context.Context, arg UpdateAccessorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAccessor, arg.Username, arg.HashedPassword, arg.Username_2)
}
